frontend:
  image: azizaman/jerney-frontend:4.0.0
  replicas: 2
  port: 80
  tag: a0fd439-1776606386
backend:
  image: azizaman/jerney-backend:3.0.0
  replicas: 2
  port: 5000
  tag: a0fd439-1776606386
postgres:
  image: postgres:15
  storage: 5Gi
ingress:
  enabled: true
  host: localhost
monitoring:
  enabled: true
  namespace: monitoring
  releaseLabel: monitoring
  path: /metrics
